name: Python Tests

on:
  push:
    branches: [ main, feat/*, fix/* ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: windows-latest
    env:
      PIP_DISABLE_PIP_VERSION_CHECK: 1
      PYTHONUNBUFFERED: 1
      TESSDATA_PREFIX: ${{ github.workspace }}\tessdata
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'
    
    - name: Install Tesseract
      run: |
        choco install -y tesseract
        tesseract --version
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Fetch tessdata (fra/ara)
      run: pwsh -File scripts/fetch_tessdata.ps1
      
    - name: Run tests
      run: |
        pytest tests/unit/test_ocr.py tests/unit/test_ocr_comprehensive.py tests/unit/test_morocco_documents.py tests/integration/test_ocr_integration.py -v
